### ISSUE TITLE
Add example usage to README.md

### ISSUE THREAD

**Issue by sancarn** [ws-garcia/VBA-CSV-interface#20]
Anyone coming to the project (me included) isn't able to actually understand how to use the project, as there is no trivial example in the readme. Would suggest adding one :)

**Comment by ws-garcia** [comment]
The Readme file has a link to [some useful usage examples](https://ws-garcia.github.io/VBA-CSV-interface/examples/).

**Comment by sancarn** [comment]
Yes, I found them after 30 minutes of searching. Would be nice if there was a simple example in the readme nevertheless.
