### ISSUE TITLE
Object doesn't support this property or method

### ISSUE THREAD

**Issue by reptileqc** [ws-garcia/VBA-CSV-interface#23]
Thank you for this project, however i'm having trouble using it.

First of all, i'm using Microsoft Access 2002 and when using the example data, i am unable to access any of the data stored in the CSVinterface object.

To Reproduce
1. Using a simple file, CRLF is the record delimiter and comma is the field delimiter. The file has slightly more than 1000 lines with 7 fields, so it's doesn't look like a size problem.
2. The parsing process seems to work without errors. The CSVint.count is reporting the right number of lines
3. When trying to extract the record or the field information (using CSVint.item(0) or CSVint.item(0, 1)), I get an error saying the "Object doesn't support this property or method"
4. I get the same error if I try to use the .DumpToArray method.

**Expected behavior**
Copying to array or trying to access the array should work

**Desktop (please complete the following information):**
- OS : Windows 10
- Microsoft Office / Access 2002 (32 bits)

**Additional context**
1. Maybe something changed in the format of the variant/arrays between 2002 and the later version of Access?
2. Using Split() to extract a delimited string to a one-dimension array works fine elsewhere in my app.

Here is the list of references I am using
![Access References](https://user-images.githubusercontent.com/7357548/132435659-3883f57b-3541-4693-a689-0c3eb6487668.png)

Here is the sample file I am using.
[SAMPLE FILE.csv](https://github.com/ws-garcia/VBA-CSV-interface/files/7125270/SAMPLE.FILE.csv)

Any help is appreciated.

Alex

**Comment by ws-garcia** [comment]
Thanks for reporting your inconvenience, I am grateful that you use CSV interface!

I think it's worth starting by clarifying one of the fundamental pillars of the CSV interface development philosophy: only the references common to all VBA projects are needed, depending on the host application. This implies that, for example, if you use Access, you do not need to activate any additional references to those already activated by default.

Regarding the error you mention, I have not been able to reproduce it, the `Item` property works as expected, even when I use the file you share with me. I could not check any error in `DumpToArray` method. I attach the screenshot.

It is very likely that you are not using the class modules properly, take a look at the [documentation](https://ws-garcia.github.io/VBA-CSV-interface/). Thanks for contributing to the project!

![Screenshot (438)](https://user-images.githubusercontent.com/70865364/132777234-40ab9726-fd5e-4b57-b6ba-ee0ebbeada7f.png)
