### ISSUE TITLE
CSVinterface.cls is encoded as UTF8 with BOM - Prevents importing as class object

### ISSUE THREAD

**Issue by Senipah** [ws-garcia/VBA-CSV-interface#3]
**Describe the bug**
CSVinterface.cls is unable to be imported as a class. When the file is added to a project, it is imported as a regular code module. 

I suspect this is due to the presence of a Byte Order Marker. See the below screenshot:
![Capture](https://user-images.githubusercontent.com/4821959/97065814-30a8f400-15a8-11eb-9ba7-54d4ebdc46f2.PNG)

**Comment by ws-garcia** [comment]
Thanks for the advice! The .cls file was updated and released.
