### ISSUE TITLE
dynamic column select when importing

### ISSUE THREAD

**Issue by shadowlips** [ws-garcia/VBA-CSV-interface#37]
I am using the following code to import from a CSV file

e.g.
`        CSVint.ImportFromCSV .parseConfig, 1, 2, 3, 4, 5, 6, 7 , 8, 9, 10`

Problem:  Unfortunately,  the source CSV file keeps changing their column position because they keep inserting new columns in between existing columns. (not at the end)

Attempted Solutions:
1.  I tried to import using column names instead of column numbers but it didn't work.  For some reason, it didn't like the column names and failed to import the columns correctly. 
2.  Then I wrote a function to find the new column numbers mapping.  e.g.   2, 3, 4, 5, 6, 7 , 8, 9, 10, 11.   But the CSVInt library won't let me import dynamic column values.   I tried putting it as string and array.  Both didn't work.

e.g.
`       NewColumnsArray() = "2, 3, 4, 5, 6, 7 , 8, 9, 10, 11"`
`       CSVint.ImportFromCSV .parseConfig, NewColumnsArray`

Question: 
    Is there a way to import columns using a variable/array?

Thank you so much!

**Comment by shadowlips** [comment]
Found a temp fix.   i duplicated and modified ImportFromCSV to take in a String variable rather than ParamsArray().

**Comment by ws-garcia** [comment]
Greetings, @shadowlips, sorry for the late reply and thank you very much for using CSV Interface in your projects. 

To import CSV files in which the columns change position we can rely on the headers.  We can read in the [documentation](https://ws-garcia.github.io/VBA-CSV-interface/api/methods/importfromcsv.html):

>User can use the `FilterColumns` parameter for retrieve only certain fields from each CSV/TSV record. The filters can be strings representing the names of the fields determined with the header record, or numbers representing the position of the requested field. If no filters defined, all the fields of the requested records will be retrieved.

Here is a code example showing the above. 

```vb
Sub CSVimportDesiredColumns()
    Dim CSVint As CSVinterface

    Set CSVint = New CSVinterface
    With CSVint.parseConfig
        .path = "C:\Sample.csv" ' Full path to the file, including its extension.
        .dialect.fieldsDelimiter = "," ' Columns delimiter
        .dialect.recordsDelimiter = vbCrLf ' Rows delimiter
    End With
    With CSVint
        .ImportFromCSV .parseConfig, _
                        1, "Revenue" ' Import 1st and "Revenue" fields ONLY
    End With
End Sub
```

In conclusion, if you know exactly the headers of the records in your CSV files, you will be able to import them without any inconvenience and without the need to modify the library.
