### ISSUE TITLE
Type abCharsets is not defined

### ISSUE THREAD

**Issue by Senipah** [ws-garcia/VBA-CSV-interface#4]
CSVinterface does not compile as it is missing a definition of the abCharsets type.

I suspect this is because the module requires a reference to a dll dependency but this is not mentioned in the documentation.

![Capture](https://user-images.githubusercontent.com/4821959/97065893-9d23f300-15a8-11eb-9304-be2160e7da5c.PNG)

Or is this library only designed to work in Access?

I manually added the below as a workaround:

```
Public Enum abCharsets
    abError = 0
    abANSI = 1
    abUnicode = 2
    abUnicodeBigEndian = 3
    abUTF8 = 4
    ebUnknown = 5
End Enum

```

**Comment by ws-garcia** [comment]
Thanks for the advice! The `.cls` file was updated and released.
