### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by zeglins** [ws-garcia/VBA-CSV-interface#40]
I had a CSV file created by excel (export spread sheet). 

The file was parse using the following code:

        Set CSVint = New CSVinterface
        
        With CSVint.parseConfig
            .dialect.recordsDelimiter = vbCrLf
            .dynamicTyping = True
            .path = name
            
        End With
        
        With CSVint
            Set .parseConfig.dialect = .SniffDelimiters(.parseConfig)
            'Debug.Print .parseConfig.dialect.fieldsDelimiter
            
            .ImportFromCSV(.parseConfig).DumpToArray arr
        End With

This code worked with other csv files. For some reason with one file it was returning arr as an array (of correct size) with empty values. I traced the problem to TypeData. The If TemplateDefined was always false. So I added an else to that if statement as below:

Private Function TypeData(ByRef data As Variant, _
                            ByVal fieldIdx As Long, _
                            ByVal IsHeader As Boolean) As Variant
    If TemplateDefined Then
        If TargetsDefined Then
            If Not IsHeader Then
                Dim typingIdx As Long, maxTypingIdx As Long
                Dim typingNeed As Boolean

                typingIdx = LBound(dTTargets)
                maxTypingIdx = UBound(dTTargets)
                Do
                    typingNeed = (fieldIdx + 1 = dTTargets(typingIdx)) 'fieldIdx is base 0
                    typingIdx = typingIdx + 1
                Loop While typingIdx <= maxTypingIdx And Not typingNeed
                If typingNeed Then
                    Select Case dTTemplate(typingIdx - 1)
                        Case TypeConversion.None 'Strings
                            TypeData = data
                        Case TypeConversion.ToLong
                            TypeData = CLng(data)
                        Case TypeConversion.ToDouble
                            TypeData = CDbl(data)
                        Case TypeConversion.ToDate
                            TypeData = CDate(data)
                        Case TypeConversion.ToBoolean
                            TypeData = CBool(data)
                        Case Else
                            TypeData = data
                    End Select
                Else
                    TypeData = data
                End If
            Else 'Not type headers
                TypeData = data
            End If
        End If
    Else    'gwz added this else
        TypeData = data
    End If
End Function

**Comment by ws-garcia** [comment]
**Thank you very much for using CSV Interface!** First of all, I think you forgot to define the [Dynamic Typing Template (DTT)](https://ws-garcia.github.io/VBA-CSV-interface/api/properties/parseconf.html) as described in the documentation:

> dynamicTyping: Gets or sets the Dynamic Typing behavior. By default, this property is set to False. If the value is set to True the parser will use the DTT to type/convert the fields linked to the template.

This is why the library is insistently requiring you to define a DTT.

[In this link I leave you an example of definition and use of the DTT](https://ws-garcia.github.io/VBA-CSV-interface/examples/advanced-examples.html#example3). 

**Please keep track of this and reply the news, my pleasure!**

**Comment by zeglins** [comment]
thanks.  This worked.

For some reason dynamicTyping was/is behaving inconsistently. I made the same error when importing other files, but they imported fine.

much appreciated!

**Comment by ws-garcia** [comment]
I will close this issue!
