### ISSUE TITLE
Compliance with RFC-8120

### ISSUE THREAD

**Issue by sdkn104** [ws-garcia/VBA-CSV-interface#8]
I hope VBA CSV interface can import any CSV that is complient with RFC-4180.

For example, Microsoft Excel write the following CSV file and it is compliant with RFC-4180,  but VBA CSV interface cannot import it in expected way.
```
"a""a"
b

 
c
```
* In the first line, double-qyite is escaped by another double-quote.
* Third line is blank line, that represent a blank field.
* Forth line contains single TAB code, that represent a TAB field.

BTW, thank you very much for updating your benchmark results.
The speed of your program is impressive, so I hope it would have an option to import fully RFC-4180 compliant CSVs.

**Comment by ws-garcia** [comment]
Thanks for your advises. I published a new release; you are free to try again! Your replies are welcome dear @sdkn104.

**Comment by ws-garcia** [comment]
In the near future, I'll make the skipping lines optional. Your are in truth, the philosophy for VBA-CSV interface is to let the user decide the way the CSV is interpreted.
